-   id: alembic-check-revisions
    name: Check Alembic migration revisions
    description: Validates that all Alembic migration files have unique down_revision values
    entry: alembic-pre-commit
    language: python
    types: [python]
    additional_dependencies: [alembic>=1.12.0] 