- id: alembic-check
  name: Check Alembic migration tool
  description: A pre-commit hook for Alembic migration tool that ensures database migration integrity and best practices
  entry: alembic-check
  language: python
  types: [python]
  args: ["YOUR_MIGRATIONS_DIRECTORY"]
